/**
 * Nerd Font icon glyph mapping for Zaroxi IDE
 * 
 * This provides a structured way to use Nerd Font icons throughout the app
 * without scattering raw Unicode glyphs across components.
 * 
 * Reference: https://www.nerdfonts.com/cheat-sheet
 */
export const nerdFontIcons = {
  // Files and folders
  'file': '',
  'file-alt': '',
  'file-code': '',
  'file-text': '',
  'file-binary': '',
  'file-archive': '',
  'file-audio': '',
  'file-video': '',
  'file-image': '',
  'file-pdf': '',
  'file-word': '',
  'file-excel': '',
  'file-powerpoint': '',
  'file-zip': '',
  'file-config': '',
  'file-json': 'ﬥ',
  'file-markdown': '',
  'file-toml': '',
  'file-yaml': '',
  'folder': '',
  'folder-open': '',
  'folder-code': '',
  'folder-git': '',
  'folder-github': '',
  'folder-npm': '',
  'folder-config': '',
  'folder-archive': '',
  
  // UI icons
  'chevron-right': '',
  'chevron-down': '',
  'chevron-left': '',
  'chevron-up': '',
  'arrow-right': '',
  'arrow-down': '',
  'arrow-left': '',
  'arrow-up': '',
  'search': '',
  'settings': '',
  'gear': '',
  'terminal': '',
  'console': '',
  'window': '',
  'layout': '',
  'menu': '',
  'list': '',
  'grid': '',
  'close': '',
  'cancel': '',
  'plus': '',
  'minus': '',
  'check': '',
  'check-circle': '',
  'error': '',
  'warning': '',
  'info': '',
  'question': '',
  'alert': '',
  'bell': '',
  'star': '',
  'heart': '',
  'pin': '',
  'tag': '',
  'bookmark': '',
  'eye': '',
  'eye-closed': '',
  'lock': '',
  'unlock': '',
  'filter': '',
  'sort': '',
  'refresh': '',
  'sync': '',
  'download': '',
  'upload': '',
  'share': '',
  'external-link': '',
  'link': '',
  'unlink': '',
  'copy': '',
  'cut': '',
  'paste': '',
  'clipboard': '',
  'scissors': '',
  'undo': '',
  'redo': '',
  'history': '',
  'time': '',
  'calendar': '',
  'clock': '',
  'home': '',
  'dashboard': '',
  'desktop': '',
  'laptop': '',
  'server': '',
  'database': '',
  'network': '',
  'cloud': '',
  'cloud-upload': '',
  'cloud-download': '',
  
  // Workspace & navigation
  'workspace': '',
  'project': '',
  'explorer': '',
  'assistant': '',
  'palette': '',
  'paintbrush': '',
  'component': '',
  'box': '',
  
  // Git
  'git-branch': '',
  'git-commit': '',
  'git-merge': '',
  'git-pull-request': '',
  'git-compare': '',
  'git-fork': '',
  'git-add': '',
  'git-push': '',
  'git-pull': '',
  'github': '',
  'gitlab': '',
  'bitbucket': '',
  
  // Editor actions
  'save': '',
  'floppy': '',
  'edit': '',
  'pencil': '',
  'trash': '',
  'archive': '',
  'book': '',
  'code': '',
  'brackets': '',
  'bug': '',
  'debug': '',
  'play': '',
  'stop': '',
  'pause': '',
  'record': '',
  'skip-forward': '',
  'skip-backward': '',
  'fast-forward': '',
  'rewind': '',
  'music': '',
  'video': '',
  
  // Programming languages
  'rust': '',
  'typescript': 'ﯤ',
  'javascript': '',
  'python': '',
  'go': '',
  'java': '',
  'c': '',
  'cpp': '',
  'csharp': '',
  'ruby': '',
  'php': '',
  'scala': '',
  'swift': '',
  'kotlin': '',
  'haskell': '',
  'elixir': '',
  'clojure': '',
  'erlang': '',
  'docker': '',
  'terraform': '',
  'kubernetes': 'ﴱ',
  'ansible': '',
  'bash': '',
  'powershell': '',
  'html': '',
  'css': '',
  'sass': '',
  'less': '',
  'json': '',
  'xml': '',
  'markdown': '',
  'database-sql': '',
  'graphql': '',
  'dart': '',
  'lua': '',
  'perl': '',
  'r': 'ﳒ',
  'julia': '',
  'elm': '',
  'ocaml': 'λ',
  'reason': '',
  'racket': '⍁',
  'fsharp': '',
  'objective-c': '',
  'vim': '',
  'zig': '',
  'crystal': '',
  'haxe': '',
  'groovy': '',
  'matlab': '',
  'purescript': '',
  'nix': '',
  'gradle': '',
  'cmake': '',
  'makefile': '',
  'shell': '',
  'solidity': '',
  'vue': '﵂',
  'svelte': '',
  'angular': '',
  'react': '',
  'ember': '',
  'backbone': '',
  'pug': '',
  'haml': '',
  'stylus': '',
  'postcss': '',
  
  // Status bar & editor indicators
  'indent': '',
  'cursor': '',
  'line-numbers': '',
  'whitespace': '␣',
  'tab': '⇥',
  'newline': '⏎',
  'lock-small': '',
  'unlock-small': '',
  'bell-slash': '',
  'mute': '',
  'volume': '',
  'fullscreen': '',
  'fullscreen-exit': '',
  'zoom-in': '',
  'zoom-out': '',
  'weather-sun': '',
  'weather-moon': '',
  'dark-mode': '',
  'light-mode': '',
  // Activity rail icons
  'sparkles': '',
  'puzzle': '',
} as const;

export type NerdFontIconName = keyof typeof nerdFontIcons;
