#!/bin/bash

echo "Zaroxi Desktop App Help"
echo "======================="
echo ""
echo "The desktop app is located in: apps/desktop/"
echo ""
echo "Common issues:"
echo "1. 'package.json not found' error"
echo "   Solution: Run commands from the apps/desktop directory"
echo ""
echo "2. 'npm install' fails"
echo "   Solution: Make sure Node.js 18+ is installed"
echo ""
echo "3. Rust dependencies not found"
echo "   Solution: Run 'cargo build --workspace' from the root directory"
echo ""
echo "Basic workflow:"
echo "cd apps/desktop"
echo "npm install"
echo "npm run tauri dev"
